# fly.toml app configuration file generated for vos-alt1-dev on 2023-11-05T19:48:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vos-alt1-dev"
primary_region = "den"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.http_options]
    [http_service.http_options.response]
      [http_service.http_options.response.headers]
        Access-Control-Allow-Headers = "*"
        Access-Control-Allow-Methods = "*"
        Access-Control-Allow-Origin = "*"
